version: "2"
services:
  # Collector
  otel-collector:
    build:
      dockerfile: Dockerfile
      context: ./images/otel-collector
    restart: always
    environment:
      - ELASTIC_APM_SECRET_TOKEN=****
      - ELASTIC_APM_SERVER_ENDPOINT=https://*****.apm.us-central1.gcp.cloud.es.io:443
    ports:
      - "1888:1888" # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  dotnet-api:
    build:
      dockerfile: Dockerfile
      context: ./images/dotnet-api
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
