receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  # not supported in 8.15
  #memory_limiter:
  #  check_interval: 1s
  #  limit_mib: 2000
  batch:

exporters:
  debug:
    verbosity: basic
  otlp/elastic:
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "${env:ELASTIC_APM_SERVER_ENDPOINT}"
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer ${env:ELASTIC_APM_SECRET_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
    logs:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
